name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    # Github Action IP 받아옥기
    - name: Get Github Actions IP
      id: ip
      uses: haythem/public-ip@v1.3

    # AWS IAM에서 USER 받아오기
    - name : AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_SECURITY_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECURITY_SECRECT_KEY }}
        aws-region: ap-northeast-2

    # GithubAction IP를 보안그룹에 추가하기
    - name : Append Github Action IP to Security group
      run: |
        aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
        
    # EC2에서 커밋 내용 저장하기
    - uses: actions/checkout@v3  
    - name : Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          script: |
            cd moatikon_backend/
            git pull
            docker compose up -d --build
      
    # 보안그룹 제거하기
    - name: Remove Gihub Actinos IP to Security group
      run: |
        aws ec2 revoke-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
